# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, 15.6
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MpeiApp' do
  config = use_native_modules!

  # yandex-mobile-ads is registered by React Native autolinking here; its
  # podspec installs the matching YandexMobileAds 8.3.0 native SDK.

  use_react_native!(
    :path => config[:reactNativePath],

    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  #pod 'mailcore2-ios'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-change-icon', :path => '../node_modules/react-native-change-icon'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNYamap', :path => '../node_modules/react-native-yamap'

  #pod 'react-native-mail', :path => '../node_modules/react-native-mail'

  pod 'MMKVCore', :modular_headers => true

  #   pod 'Firebase', :modular_headers => true
  #   pod 'FirebaseCoreInternal', :modular_headers => true
  #   pod 'GoogleUtilities', :modular_headers => true
  #   pod 'FirebaseCore', :modular_headers => true
  #pod 'FirebaseCoreExtension'#, :modular_headers => true 
  #pod 'FirebaseAppCheckInterop'#, :modular_headers => true
  #pod 'FirebaseAuthInterop'#, :modular_headers => true
  #pod 'FirebaseMessagingInterop'#, :modular_headers => true
  #pod 'GTMSessionFetcher'#, :modular_headers => true

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
        installer,
        config[:reactNativePath],
        :mac_catalyst_enabled => false,
        # :ccache_enabled => true
    )
    bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
    def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
      framework_path = File.join(Dir.pwd, framework_relative_path)
      command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
      puts "Stripping bitcode: #{command}"
      system(command)
    end

    framework_paths = [
         "Pods/LogRocket/LogRocket.xcframework/ios-arm64/LogRocket.framework/LogRocket",
         "Pods/hermes-engine/destroot/Library/Frameworks/macosx/hermes.framework/hermes",
         "Pods/hermes-engine/destroot/Library/Frameworks/macosx/hermes.framework/Versions/Current/hermes",
         "Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64/hermes.framework/hermes",
         "Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-maccatalyst/hermes.framework/hermes"
    ]

    framework_paths.each do |framework_relative_path|
      strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
    end
  end
end
